version: '3'
services:

  scylla00:
    image: scylladb/scylla-with-agent
    container_name: scylla00
    restart: unless-stopped
    command: --seeds=scylla00 --memory 1G --smp 1 --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
      - "scylla00:/var/lib/scylla"
    ports:
      - "${SCYLLA_PORT00}"
      - "${SCYLLA_PROMPORT00}"
    networks:
      - scylla-network

  scylla01:
    image: scylladb/scylla-with-agent
    container_name: scylla01
    restart: unless-stopped
    command: --seeds=scylla00 --memory 1G --smp 1 --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
      - "scylla01:/var/lib/scylla"
    ports:
      - "${SCYLLA_PORT01}"
      - "${SCYLLA_PROMPORT01}"
    networks:
      - scylla-network

  scylla02:
    image: scylladb/scylla-with-agent
    container_name: scylla02
    restart: unless-stopped
    command: --seeds=scylla00 --memory 1G --smp 1 --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
      - "scylla02:/var/lib/scylla"
    ports:
      - "${SCYLLA_PORT02}"
      - "${SCYLLA_PROMPORT02}"
    networks:
      - scylla-network

  minio:
    image: minio/minio
    container_name: builder_agent_scylla
    volumes:
      - "./minio_data:/data"
    networks:
      scylla-network:
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    
networks:
  scylla-network:
    name: scylla-network
    driver: bridge

volumes:
  minio_data: ~
  scylla00: ~
  scylla01: ~
  scylla02: ~
