version: '3.7'
# Settings and configurations that are common for all containers
x-scylla-common: &scylla-common
  image: scylladb/scylla-with-agent
  build:
    context: ./
    dockerfile: ./Dockerfile
  restart: unless-stopped
  command: --seeds=scylla00 --memory 1G --smp 1 --overprovisioned 1 --api-address 0.0.0.0
  networks:
    - scylla-network

services:
  scylla00:
    <<: *scylla-common
    container_name: scylla00
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
      - "scylla00:/var/lib/scylla"
    ports:
      - "${SCYLLA_PORT00}"
      - "${SCYLLA_PROMPORT00}"
    

  scylla01:
    <<: *scylla-common
    container_name: scylla01
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
      - "scylla01:/var/lib/scylla"
    ports:
      - "${SCYLLA_PORT01}"
      - "${SCYLLA_PROMPORT01}"

  scylla02:
    <<: *scylla-common
    container_name: scylla02
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
      - "scylla02:/var/lib/scylla"
    ports:
      - "${SCYLLA_PORT02}"
      - "${SCYLLA_PROMPORT02}"

  minio:
    image: minio/minio
    profiles:
      - minio
    container_name: minio
    volumes:
      - "./minio_data:/data"
    networks:
      scylla-network:
    ports:
      - "9001:9000"
      - "39049:39049"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":39049"
    
networks:
  scylla-network:
    name: scylla-network
    driver: bridge

volumes:
  minio_data: ~
  scylla00: ~
  scylla01: ~
  scylla02: ~
