version: "3"

services:
  scylla-manager:
    image: scylladb/scylla-manager
    container_name: scylla-manager
    networks:
      - scylla-network
    depends_on:
      - scylla-manager-db
    volumes:
      - "./scylla-manager.yaml:/etc/scylla/scylla-manager.yaml"

  scylla-manager-db:
    image: scylladb/scylla
    container_name: scylla-manager-db
    volumes:
      - "./scylla_manager_db_data:/var/lib/scylla"
    networks:
      - scylla-network
    command: --smp 1 --memory 100M

volumes:
  scylla_manager_db_data: ~

networks:
  scylla-network:
    name: scylla-network
    driver: bridge
